### ISSUE TITLE
Add link to Git Repo on project page

### ISSUE THREAD

**Issue by theryankelly** [codeisland/RI-Budget-Sankey#3]
At bottom we need to add a link to Git Repo on /RI-Budget-Sankey.

Either text or octocat logo link.

**Comment by ghost** [comment]
I will jump in and execute this and the column height explanatory text. Question for @jamesrhaley and @nelsonri72: would you rather I branch this and do a pull request or just edit the html directly. I will steer well clear of the sankey, so no worries there.

**Comment by nelsonri72** [comment]
I'm ok with just an edit if James has no objections

**Comment by goldenmeanie** [comment]
This appears to be done. Thanks @Frymasterspeck!
