### ISSUE TITLE
Align "Agency" title to proper place above 3rd column.

### ISSUE THREAD

**Issue by nelsonri72** [codeisland/RI-Budget-Sankey#5]
Align "Agency" title to proper place above 3rd column.  Defect may be related to "RI Higher Education Assistance Auth" Fund not aligning properly below middle fund column. 
![align agency title above 3rd column](https://cloud.githubusercontent.com/assets/7595000/6139411/525806fe-b159-11e4-8abc-ea853c80385a.JPG)

**Comment by jamesrhaley** [comment]
This has now been updated and the tooltip style was updated as well.

**Comment by nelsonri72** [comment]
Fixed. Created #6 for rogue fund not aligning in middle column
